name: build-macos (arm64 & intel)

on:
  push:
    tags: ['v*', 'release-*']
  workflow_dispatch:

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: false

env:
  APP_NAME: HyoukiYureCheck
  ENTRYPOINT: hyouki_yure_check.py

jobs:
  build:
    name: macOS ${{ matrix.runner }} • PyInstaller
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-14, macos-15-intel]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "fugashi[unidic-lite]" PyMuPDF PySide6 pandas
            pip install xlsxwriter openpyxl
          fi
          pip install pyinstaller

      - name: Sanity check DICDIR
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import unidic_lite
          print("unidic_lite.DICDIR =", getattr(unidic_lite, "DICDIR", None))
          PY

      - name: Sanity check imports
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import xlsxwriter, openpyxl
          print("xlsxwriter:", xlsxwriter.__version__)
          print("openpyxl  :", openpyxl.__version__)
          PY

      - name: Build (.app) with PyInstaller
        shell: bash
        run: |
          set -euo pipefail
          echo "ENTRYPOINT=$ENTRYPOINT"
          if [ ! -f "$ENTRYPOINT" ]; then
            echo "::error title=ENTRYPOINT not found::'$ENTRYPOINT' が見つかりません。env.ENTRYPOINT と実ファイル名/パスを確認してください。"
            echo "リポジトリのルート内容:"; ls -al
            exit 1
          fi

          pyinstaller --noconfirm --clean --windowed \
            --name "$APP_NAME" \
            --hidden-import fitz \
            --hidden-import unidic_lite \
            --hidden-import xlsxwriter \
            --hidden-import openpyxl \
            --hidden-import et_xmlfile \
            --collect-data unidic_lite \
            --collect-data fugashi \
            "$ENTRYPOINT"

      - name: Pack .dmg (compressed) & keep only .dmg
        shell: bash
        run: |
          set -euo pipefail
          cd dist
          APP="${APP_NAME}.app"
          DMG="${APP_NAME}-${{ matrix.runner }}.dmg"
          hdiutil create -volname "${APP_NAME}" -srcfolder "${APP}" -ov -format UDZO "${DMG}"
          rm -rf "${APP}"

      - name: Upload artifact (.dmg only)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-macos-${{ env.APP_NAME }}
          path: dist/${{ env.APP_NAME }}-${{ matrix.runner }}.dmg
